Naming/FileName:
  Exclude:
    - lib/rubocop-teachbase.rb
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 100
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes

